# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 09:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='title')),
                ('model', models.CharField(blank=True, default='', max_length=50, verbose_name='model')),
                ('imei', models.CharField(blank=True, default='', max_length=18, verbose_name='IMEI')),
                ('phone_number', models.CharField(blank=True, default='', max_length=32, verbose_name='phone number')),
                ('mac', models.CharField(blank=True, default='', max_length=20, verbose_name='mac')),
                ('usb_id_code', models.CharField(blank=True, default='', max_length=30, verbose_name='usb id code')),
                ('latitude', models.CharField(blank=True, default='', max_length=50, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, default='', max_length=50, verbose_name='longitude')),
                ('height', models.CharField(blank=True, default='', max_length=50, verbose_name='height')),
                ('cell_id', models.BooleanField(default=False, verbose_name='cell id')),
                ('ip_info', models.CharField(blank=True, default='', max_length=128, verbose_name='ip info')),
                ('wifi_info', models.CharField(blank=True, default='', max_length=512, verbose_name='wifi info')),
                ('battery_info', models.CharField(blank=True, default='', max_length=128, verbose_name='battery info')),
                ('webcam_picture', models.CharField(blank=True, default='', max_length=128, verbose_name='webcam picture')),
                ('code', models.TextField(verbose_name='code')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name_plural': 'devices',
                'verbose_name': 'device',
                'ordering': ('created',),
            },
        ),
    ]
